### ISSUE TITLE
Update the new alumni

### ISSUE THREAD

**Issue by madhumithanara** [IE-NITK/ie-website#108]

**Comment by madhumithanara** [comment]
Updated new core. Yet to collect LinkedIn information for 2020 batch, this issue is on hold.

**Comment by chaitany10** [comment]
@Paranjaysaxena can u take this up?

**Comment by chaitany10** [comment]
@PiyushPI07 @Paranjaysaxena @dhanwin247 @Omanshu840 @Shreesha-B  one of u take this up on urgent basis
