### ISSUE TITLE
Flagship Event Content Overflow

### ISSUE THREAD

**Issue by madhumithanara** [IE-NITK/ie-website#154]
![image](https://user-images.githubusercontent.com/38850744/95992476-9d571c80-0e4b-11eb-9280-2831829b28b4.png)

Upon magnifying it, 

![image](https://user-images.githubusercontent.com/38850744/95992557-b233b000-0e4b-11eb-9bc8-63efaeb4657a.png)

This also seems to be the issue with all cards in events as well. Content in the cards need to be contained irrespective of the screen resolution/magnification.

**Comment by SaishMendke** [comment]
@madhumithanara I think changing the font-size in the events.html file in the events folder from 1.2em to 1.2vw and increasing the size of card can fix this issue. Can I work on it?

**Comment by madhumithanara** [comment]
Hi @SaishMendke 

Please try a different method. The cards should always be relatively sized with the text, hence ensuring screen size independence.

Also, please revert the changes to settings.py before pushing code.

**Comment by SaishMendke** [comment]
@madhumithanara Okay.
