### ISSUE TITLE
New Logos for the Club/SIG

### ISSUE THREAD

**Issue by mishal23** [IE-NITK/ie-website#3]
- [x] Club Logo
- [x] Code
- [x] Gadget
- [x] Garage
- [x] Capital
- [x] Media
- [x] Robotics
- [x] Script

**Comment by chaitany10** [comment]
@mishal23 What's the status about this, is it still relevant?

**Comment by mishal23** [comment]
As of last year, all the logos were created/re-used. If there's a plan to make new ones, please go ahead 😄 

cc: @sjs253 @madhumithanara @devil-r @krahulreddy all others

**Comment by madhumithanara** [comment]
Let us close this issue?

@chaitany10  @mishal23
